INSERT INTO EMPLOYEE ( FIRST_NAME, LAST_NAME, METADATA) VALUES ('Mike', 'Miller', 'junk' );
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, METADATA) VALUES ( 'Elena', 'Miller', 'elena-junk');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, METADATA) VALUES ( 'Kathryn', 'Miller', 'pwd=test');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, METADATA) VALUES ( 'Don', 'Miller', 'job=NASA Rocket Scientist');